name: knobgen
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pytorch=2.3.1
  - torchvision=0.18.1
  - torchaudio=2.3.1
  - pytorch-cuda=12.1
  - pip
  - pip:
    - diffusers==0.29.2
    - accelerate==0.31.0
    - transformers==4.42.3
    - omegaconf
    - wandb
    - opencv-python